version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lemp_db
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lemp-docker

  www:
    depends_on:
      - db
    image: webdevops/php-nginx:8.2
    volumes:
      - "./html:/app"
    ports:
      - 80:80
      - 443:443
    networks:
      - lemp-docker

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3307
    networks:
      - lemp-docker
    volumes:
      - phpmyadmin-data:/sessions

networks:
  lemp-docker:
    driver: bridge

volumes:
  phpmyadmin-data: